[package]
name = "opal-derive"
version = "0.1.0"
edition = "2021"
description = "opal is a simple static webapp to look up the IPA phonetics of English words, or vice versa."

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"